### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Amb33r** [kosciolek/vider.info-downloader#1]
hellp :) 

![image](https://user-images.githubusercontent.com/70627077/153193295-a1a24352-3f5b-428f-86bf-f9b8db1127c5.png)

**Comment by kosciolek** [comment]
Thanks for reporting it. I'll try to fix it today.

**Comment by Amb33r** [comment]
Dzięki kolego.

**Comment by kosciolek** [comment]
Sfixowalem, u mnie juz dziala.

Zupdatuj do najnowszej wersji. `npm update -g @vider-downloader/cli` powinno zadzialac, jak nie to uninstall/install zrob.

Alternatywnie, pojdz do `C:\Users\Damian\AppData\Roaming\npm\node_modules\@vider-downloader\cli\node_modules\@vider-downloader\core\dist\fetchVideoMetadata.js` i zmien
```
/data-video-url="https:\/\/stream\.vider\.info\/video\/(\d+)\/v\.mp4"/
```
na 
```
/data-video-url="https:\/\/stream\.vider\.info\/video\/(\d+)\/v\.mp4/
```
(usunalem jedno `"`na koncu linii).

Potem juz powinno dzialac. Jesli dalej nie dziala, to wejdz na videra i rozwiaz captcha kilka razy (az sie odblokuje).

**Comment by kosciolek** [comment]
@Amb33r 
Sfixowalem, u mnie juz dziala.

Zupdatuj do najnowszej wersji. `npm update -g @vider-downloader/cli` powinno zadzialac, jak nie to uninstall/install zrob.

Alternatywnie, pojdz do `C:\Users\Damian\AppData\Roaming\npm\node_modules\@vider-downloader\cli\node_modules\@vider-downloader\core\dist\fetchVideoMetadata.js` i zmien
```
/data-video-url="https:\/\/stream\.vider\.info\/video\/(\d+)\/v\.mp4"/
```
na 
```
/data-video-url="https:\/\/stream\.vider\.info\/video\/(\d+)\/v\.mp4/
```
(usunalem jedno `"`na koncu linii).

Potem juz powinno dzialac. Jesli dalej nie dziala, to wejdz na videra i rozwiaz captcha kilka razy (az sie odblokuje).

**Comment by Amb33r** [comment]
Dziękuje za szybką reakcje pomogło dopiero usuniecie 👍 
(usunalem jedno "na koncu linii).

Pozdrawiam serdecznie
