### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by Iicytower** [kosciolek/vider.info-downloader#3]
I just install the cli and wany to use it, but receive `TypeError`

![image](https://user-images.githubusercontent.com/37587581/215156940-f0578e42-53c2-428a-8922-0b88be608a0b.png)

**Comment by JustRad123** [comment]
same man , all this effort into downloading this and now it doesnw even work

**Comment by kosciolek** [comment]
Sorry guys, i should put a note this is outdated and vider's website probably has changed enough for this tool not to work at this point. Ill perhaps update it in a while

**Comment by kosciolek** [comment]
should work now, i wrote a new script
